export const TOOLBAR_ACTION_IDS = Object.freeze({
  SELECT: "SELECT",
  MOVE: "MOVE",
  MOVE_OFF: "MOVE_OFF",
  MOVE_PLANAR: "MOVE_PLANAR",
  ROTATE: "ROTATE",
  NAVIGATE: "NAVIGATE",
  AREA_SELECT: "AREA_SELECT",
  BUILDING_TRANSPARENCY: "BUILDING_TRANSPARENCY",
  FOCUS_BUILDING: "FOCUS_BUILDING",
  HIDE_SURROUNDINGS: "HIDE_SURROUNDINGS",
  SHADOW: "SHADOW",
  HIGH_PRECISION_MODEL: "HIGH_PRECISION_MODEL",
  FLOOR_GAP: "FLOOR_GAP",
  FLOOR_SELECT: "FLOOR_SELECT",
  MOVEMENT_PATH: "MOVEMENT_PATH",
  PLAY: "PLAY",
  PAUSE: "PAUSE",
  STOP: "STOP",
  GROUND_VISIBLE: "GROUND_VISIBLE",
  GROUND_TRANSLUCENT: "GROUND_TRANSLUCENT",
  GROUND_SECTION: "GROUND_SECTION",
  GROUND_HIDDEN: "GROUND_HIDDEN",
  UNDO: "UNDO",
  REDO: "REDO",
});

export const TOOLBAR_ACTIONS = Object.freeze({
  [TOOLBAR_ACTION_IDS.SELECT]: { label: "선택", shortcut: "V", iconKey: "select" },
  [TOOLBAR_ACTION_IDS.MOVE]: { label: "전체 이동", shortcut: "W", iconKey: "move" },
  [TOOLBAR_ACTION_IDS.MOVE_OFF]: { label: "이동 꺼짐", shortcut: "W", iconKey: "move-off" },
  [TOOLBAR_ACTION_IDS.MOVE_PLANAR]: { label: "평면 이동", shortcut: "W", iconKey: "move-planar" },
  [TOOLBAR_ACTION_IDS.ROTATE]: { label: "회전", shortcut: "E", iconKey: "rotate" },
  [TOOLBAR_ACTION_IDS.NAVIGATE]: { label: "월드 회전", iconKey: "navigate" },
  [TOOLBAR_ACTION_IDS.AREA_SELECT]: { label: "영역 선택", iconKey: "area-select" },
  [TOOLBAR_ACTION_IDS.BUILDING_TRANSPARENCY]: { label: "건축물 반투명", iconKey: "transparency" },
  [TOOLBAR_ACTION_IDS.FOCUS_BUILDING]: { label: "선택 건축물만 보기", iconKey: "isolate" },
  [TOOLBAR_ACTION_IDS.HIDE_SURROUNDINGS]: { label: "주변 요소 숨기기", iconKey: "hide-surroundings" },
  [TOOLBAR_ACTION_IDS.SHADOW]: { label: "그림자 표시", iconKey: "shadow" },
  [TOOLBAR_ACTION_IDS.HIGH_PRECISION_MODEL]: { label: "고정밀 모델 유지", iconKey: "high-detail" },
  [TOOLBAR_ACTION_IDS.FLOOR_GAP]: { label: "층 간격", iconKey: "floor-spacing" },
  [TOOLBAR_ACTION_IDS.FLOOR_SELECT]: { label: "층 선택", iconKey: "floor-select" },
  [TOOLBAR_ACTION_IDS.MOVEMENT_PATH]: { label: "이동경로 편집", iconKey: "path-edit" },
  [TOOLBAR_ACTION_IDS.PLAY]: { label: "재생", shortcut: "Space", iconKey: "play" },
  [TOOLBAR_ACTION_IDS.PAUSE]: { label: "일시정지", shortcut: "Space", iconKey: "pause" },
  [TOOLBAR_ACTION_IDS.STOP]: { label: "정지", iconKey: "stop" },
  [TOOLBAR_ACTION_IDS.GROUND_VISIBLE]: { label: "지면 표시", iconKey: "ground-visible" },
  [TOOLBAR_ACTION_IDS.GROUND_TRANSLUCENT]: { label: "지면 반투명", iconKey: "ground-translucent" },
  [TOOLBAR_ACTION_IDS.GROUND_SECTION]: { label: "지면 단면", iconKey: "ground-section" },
  [TOOLBAR_ACTION_IDS.GROUND_HIDDEN]: { label: "지면 숨기기", iconKey: "ground-hidden" },
  [TOOLBAR_ACTION_IDS.UNDO]: { label: "되돌리기", shortcut: "Ctrl+Z", iconKey: "undo" },
  [TOOLBAR_ACTION_IDS.REDO]: { label: "다시 실행", shortcut: "Ctrl+Shift+Z", iconKey: "redo" },
});

export function getToolbarAction(actionId) {
  return TOOLBAR_ACTIONS[actionId] ?? null;
}
